### PR TITLE
fix(select) re-render pre-selection on collection change to fix diver…

### LINKED ISSUE #61: abp-select selection diverges when changing item collection
When I alter the item collection bound to a `abp-select` then the bound `selectedItem` and `selectedValue` properties diverge from the effective selection in the underlying html `select` element.

### PR DESCRIPTION
**Pull request by Mobe91**
fixes #61

### CODE REVIEW

File: aurelia-bootstrap-select/src/abp-select.js [hunk 1]
```diff
@@ -228,6 +228,7 @@ export class AbpSelectCustomElement {
   collectionChangedObserver(newCollection, oldCollection) {
     setTimeout(() => {
       this.domElm.selectpicker('refresh');
+      this.renderPreSelection();
```
Comment (ghiscoding) [inline aurelia-bootstrap-select/src/abp-select.js:231]: I'm not sure if it would make any differences but isn't the DOM element refresh supposed to be at the end (after updating values)?

**Comment by ghiscoding** [comment]
pushed a new version `1.3.3` on [NPM](https://www.npmjs.com/package/aurelia-bootstrap-select), again thanks for the multiple contributions
